# Generated by Django 5.0.6 on 2024-07-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='reference_address',
            new_name='reader_address',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='reference_cantact',
            new_name='reader_cantact',
        ),
        migrations.RenameField(
            model_name='reader',
            old_name='reference_name',
            new_name='reader_name',
        ),
    ]
